version: "3.7"

services:
  consul-server:
    image: hashicorp/consul:1.12.0
    container_name: consul-server
    restart: unless-stopped
    volumes:
      - ./config/consul-server.json:/consul/config/consul-server.json:ro
      - ./cert/:/consul/config/certs/:ro
    networks:
      mynet:
        ipv4_address: 172.20.0.5
    ports:
      - "8500:8500"
      - "8300:8300"
      - "8301:8301"
      - "8302:8302"
      - "53:53/tcp"
      - "53:53/udp"
    command: "agent"
    dns:
      - "8.8.8.8"
      - "8.8.8.4"

  consul-client:
    image: hashicorp/consul:1.12.0
    container_name: consul-client
    restart: unless-stopped
    networks:
      mynet:
        ipv4_address: 172.20.0.6
    volumes:
      - ./config/consul-client.json:/consul/config/consul-client.json:ro
      - ./cert/:/consul/config/certs/:ro
    command: "agent"
    dns:
      - "8.8.8.8"
      - "8.8.8.4"
    depends_on:
      - "consul-server"

networks:
  mynet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16